#write dockerfile for php
version: '3.5'


services:
    app-php:
        container_name: app-php
        build:
            context: ../
            dockerfile: docker/php/Dockerfile
        image: php-blackjack:php-blackjack
        volumes:
            - .:/app
        env_file:
            - docker-compose.env
    nginx:
        container_name: app-nginx
        build:
            context: ./nginx
        volumes:
            - ../app:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "669:80"
